import 'package:flutter/material.dart';

import 'models.dart';

Word _w(String slug, String en, String ru) {
  return Word(id: '$slug-${en.replaceAll(' ', '-')}', en: en, ru: ru);
}

Category _cat(
  String slug,
  String title,
  String subtitle,
  IconData icon,
  List<(String, String)> entries,
) {
  return Category(
    slug: slug,
    title: title,
    subtitle: subtitle,
    icon: icon,
    words: [for (final e in entries) _w(slug, e.$1, e.$2)],
  );
}

final List<Category> kCategories = [
  _cat('basics', 'Основы', 'Everyday words', Icons.menu_book_outlined, [
    ('hello', 'привет'),
    ('goodbye', 'пока'),
    ('please', 'пожалуйста'),
    ('thanks', 'спасибо'),
    ('yes', 'да'),
    ('no', 'нет'),
    ('water', 'вода'),
    ('food', 'еда'),
    ('friend', 'друг'),
    ('house', 'дом'),
    ('book', 'книга'),
    ('time', 'время'),
    ('day', 'день'),
    ('night', 'ночь'),
    ('name', 'имя'),
    ('love', 'любовь'),
    ('life', 'жизнь'),
    ('world', 'мир'),
  ]),
  _cat('food', 'Еда', 'Meals and taste', Icons.restaurant_outlined, [
    ('apple', 'яблоко'),
    ('bread', 'хлеб'),
    ('milk', 'молоко'),
    ('cheese', 'сыр'),
    ('meat', 'мясо'),
    ('fish', 'рыба'),
    ('egg', 'яйцо'),
    ('tea', 'чай'),
    ('coffee', 'кофе'),
    ('sugar', 'сахар'),
    ('salt', 'соль'),
    ('soup', 'суп'),
    ('rice', 'рис'),
    ('fruit', 'фрукт'),
    ('breakfast', 'завтрак'),
    ('dinner', 'ужин'),
    ('restaurant', 'ресторан'),
    ('kitchen', 'кухня'),
  ]),
  _cat('travel', 'Путешествия', 'On the road', Icons.flight_outlined, [
    ('ticket', 'билет'),
    ('passport', 'паспорт'),
    ('airport', 'аэропорт'),
    ('train', 'поезд'),
    ('hotel', 'отель'),
    ('map', 'карта'),
    ('luggage', 'багаж'),
    ('city', 'город'),
    ('country', 'страна'),
    ('beach', 'пляж'),
    ('road', 'дорога'),
    ('flight', 'рейс'),
    ('guide', 'гид'),
    ('tourist', 'турист'),
    ('border', 'граница'),
    ('journey', 'путешествие'),
    ('station', 'вокзал'),
    ('taxi', 'такси'),
  ]),
  _cat('home', 'Дом', 'Rooms and things', Icons.home_outlined, [
    ('room', 'комната'),
    ('window', 'окно'),
    ('door', 'дверь'),
    ('table', 'стол'),
    ('chair', 'стул'),
    ('bed', 'кровать'),
    ('lamp', 'лампа'),
    ('key', 'ключ'),
    ('wall', 'стена'),
    ('floor', 'пол'),
    ('kitchen', 'кухня'),
    ('bathroom', 'ванная'),
    ('mirror', 'зеркало'),
    ('shelf', 'полка'),
    ('clock', 'часы'),
    ('pillow', 'подушка'),
    ('blanket', 'одеяло'),
    ('garden', 'сад'),
  ]),
  _cat('nature', 'Природа', 'Outdoors', Icons.park_outlined, [
    ('tree', 'дерево'),
    ('flower', 'цветок'),
    ('river', 'река'),
    ('mountain', 'гора'),
    ('sun', 'солнце'),
    ('moon', 'луна'),
    ('rain', 'дождь'),
    ('snow', 'снег'),
    ('wind', 'ветер'),
    ('sky', 'небо'),
    ('forest', 'лес'),
    ('sea', 'море'),
    ('stone', 'камень'),
    ('grass', 'трава'),
    ('cloud', 'облако'),
    ('star', 'звезда'),
    ('lake', 'озеро'),
    ('earth', 'земля'),
  ]),
  _cat('animals', 'Животные', 'Creatures', Icons.pets_outlined, [
    ('cat', 'кот'),
    ('dog', 'собака'),
    ('bird', 'птица'),
    ('fish', 'рыба'),
    ('horse', 'лошадь'),
    ('cow', 'корова'),
    ('bear', 'медведь'),
    ('wolf', 'волк'),
    ('fox', 'лиса'),
    ('rabbit', 'кролик'),
    ('mouse', 'мышь'),
    ('lion', 'лев'),
    ('tiger', 'тигр'),
    ('elephant', 'слон'),
    ('duck', 'утка'),
    ('bee', 'пчела'),
    ('snake', 'змея'),
    ('frog', 'лягушка'),
  ]),
  _cat('work', 'Работа', 'Office and craft', Icons.work_outline, [
    ('job', 'работа'),
    ('office', 'офис'),
    ('meeting', 'встреча'),
    ('letter', 'письмо'),
    ('computer', 'компьютер'),
    ('phone', 'телефон'),
    ('money', 'деньги'),
    ('boss', 'начальник'),
    ('team', 'команда'),
    ('project', 'проект'),
    ('salary', 'зарплата'),
    ('plan', 'план'),
    ('task', 'задача'),
    ('paper', 'бумага'),
    ('desk', 'письменный стол'),
    ('email', 'почта'),
    ('client', 'клиент'),
    ('deadline', 'срок'),
  ]),
  _cat('emotions', 'Эмоции', 'How you feel', Icons.favorite_border, [
    ('happy', 'счастливый'),
    ('sad', 'грустный'),
    ('angry', 'злой'),
    ('tired', 'усталый'),
    ('scared', 'испуганный'),
    ('calm', 'спокойный'),
    ('proud', 'гордый'),
    ('lonely', 'одинокий'),
    ('kind', 'добрый'),
    ('brave', 'храбрый'),
    ('shy', 'застенчивый'),
    ('funny', 'смешной'),
    ('bored', 'скучающий'),
    ('surprised', 'удивлённый'),
    ('hope', 'надежда'),
    ('fear', 'страх'),
    ('joy', 'радость'),
    ('peace', 'покой'),
  ]),
  _cat('verbs', 'Глаголы', 'Actions', Icons.bolt_outlined, [
    ('go', 'идти'),
    ('see', 'видеть'),
    ('know', 'знать'),
    ('speak', 'говорить'),
    ('make', 'делать'),
    ('take', 'брать'),
    ('give', 'давать'),
    ('come', 'приходить'),
    ('think', 'думать'),
    ('want', 'хотеть'),
    ('eat', 'есть'),
    ('drink', 'пить'),
    ('sleep', 'спать'),
    ('work', 'работать'),
    ('live', 'жить'),
    ('read', 'читать'),
    ('write', 'писать'),
    ('learn', 'учить'),
  ]),
  _cat('city', 'Город', 'Around town', Icons.location_city_outlined, [
    ('street', 'улица'),
    ('shop', 'магазин'),
    ('school', 'школа'),
    ('hospital', 'больница'),
    ('park', 'парк'),
    ('bridge', 'мост'),
    ('museum', 'музей'),
    ('library', 'библиотека'),
    ('bank', 'банк'),
    ('market', 'рынок'),
    ('square', 'площадь'),
    ('bus', 'автобус'),
    ('metro', 'метро'),
    ('cinema', 'кинотеатр'),
    ('cafe', 'кафе'),
    ('church', 'церковь'),
    ('police', 'полиция'),
    ('pharmacy', 'аптека'),
    ('car park', 'парковка'),
    ('bus stop', 'остановка'),
    ('gym', 'спортзал'),
    ('coffee shop', 'кофейня'),
    ('shopping mall', 'торговый центр'),
    ('swimming pool', 'бассейн'),
    ('post office', 'почта'),
    ('petrol station', 'заправка'),
    ('underground station', 'станция метро'),
    ('fire station', 'пожарная'),
    ('police station', 'полиция'),
  ]),
  _cat('restaurant', 'Ресторан', 'Eating out', Icons.dinner_dining_outlined, [
    ('bill', 'счёт'),
    ('tips', 'чаевые'),
    ('order', 'заказ'),
    ('make an order', 'сделать заказ'),
    ('cuisine', 'кухня'),
    ('eat out', 'есть вне дома'),
    ('book a table', 'забронировать столик'),
    ('waiter', 'официант'),
    ('waitress', 'официантка'),
    ('savoury food', 'несладкое блюдо'),
    ('cutlery', 'приборы'),
    ('napkin', 'салфетка'),
    ('starter', 'закуска'),
    ('main course', 'основное блюдо'),
    ('dessert', 'десерт'),
    ('set menu', 'комплексный обед'),
    ('beverage', 'напиток'),
  ]),
  _cat('directions', 'Дорога', 'Asking for directions', Icons.directions_outlined, [
    ('head south', 'идти на юг'),
    ('head north', 'идти на север'),
    ('head east', 'идти на восток'),
    ('head west', 'идти на запад'),
    ('turn right', 'направо'),
    ('turn left', 'налево'),
    ('go straight', 'прямо'),
    ('cross the street', 'перейти улицу'),
    ('on the corner', 'на углу'),
    ('next to the bank', 'рядом с банком'),
    ('opposite the cafe', 'напротив кафе'),
    ('go past the cafe', 'мимо кафе'),
    ('follow the signs', 'по указателям'),
    ('go under the bridge', 'под мостом'),
    ('roundabout', 'кольцо'),
    ('second exit', 'второй съезд'),
    ('lost', 'заблудился'),
  ]),
  _cat('social', 'Соцсети', 'Phone actions', Icons.phone_iphone_outlined, [
    ('unfollow', 'отписаться'),
    ('comment on', 'комментировать'),
    ('voice note', 'голосовое'),
    ('delete', 'удалить'),
    ('reply', 'ответить'),
    ('screenshot', 'скриншот'),
    ('tag', 'отметить'),
    ('post', 'опубликовать'),
  ]),
  _cat('chores', 'Дом', 'Housework', Icons.cleaning_services_outlined, [
    ('take out the bins', 'вынести мусор'),
    ('unpack groceries', 'разобрать продукты'),
    ('fold the washing', 'сложить бельё'),
    ('sweep the floor', 'подмести'),
    ('wipe surfaces', 'протереть'),
    ('mop the floor', 'мыть пол'),
    ('load dishwasher', 'загрузить посудомойку'),
    ('unload dishwasher', 'выгрузить посудомойку'),
    ('wash the worktop', 'вымыть стол'),
    ('restock toilet roll', 'положить бумагу'),
    ('vacuum the carpet', 'пропылесосить'),
  ]),
  _cat('travel_talk', 'В дороге', 'Travel phrases', Icons.luggage_outlined, [
    ("I can't imagine", 'не могу представить'),
    ("I've never managed", 'никогда не получалось'),
    ('I miss', 'я скучаю'),
    ('I hope', 'я надеюсь'),
    ("I'd like to learn", 'хочу выучить'),
    ('I love', 'я люблю'),
    ('I hate', 'я ненавижу'),
    ("I've decided", 'я решил'),
    ('I never finish', 'не заканчиваю'),
    ('I prefer', 'я предпочитаю'),
  ]),

  _cat('frequency', 'Частота', 'How often', Icons.tune, [
    ('never', 'никогда'),
    ('rarely', 'редко'),
    ('sometimes', 'иногда'),
    ('often', 'часто'),
    ('usually', 'обычно'),
    ('always', 'всегда'),
  ]),
  _cat('pets', 'Питомцы', 'Pet care', Icons.pets, [
    ('feed', 'кормить'),
    ('walk', 'выгуливать'),
    ('play', 'играть'),
    ('groom', 'ухаживать за шерстью'),
    ('train', 'дрессировать'),
    ('pet', 'гладить'),
    ('clean up', 'убирать за животным'),
    ('bathe', 'купать'),
    ('cuddle', 'обнимать'),
  ]),
  _cat('crime', 'Преступления', 'Crime words', Icons.gavel, [
    ('theft', 'кража'),
    ('thief', 'вор'),
    ('steal', 'красть'),
    ('robbery', 'ограбление'),
    ('robber', 'грабитель'),
    ('burglary', 'взлом'),
    ('burglar', 'взломщик'),
    ('mugging', 'уличное ограбление'),
    ('shoplifting', 'кража в магазине'),
    ('arson', 'поджог'),
    ('smuggling', 'контрабанда'),
    ('looting', 'мародёрство'),
    ('kidnapping', 'похищение'),
    ('murder', 'убийство'),
    ('vandalism', 'вандализм'),
    ('forgery', 'подделка'),
  ]),
  _cat('irregular1', 'Глаголы 1', 'Irregular A–G', Icons.bolt_outlined, [
    ('be', 'быть'),
    ('beat', 'бить'),
    ('become', 'становиться'),
    ('begin', 'начинать'),
    ('bend', 'гнуть'),
    ('bite', 'кусать'),
    ('blow', 'дуть'),
    ('break', 'ломать'),
    ('bring', 'приносить'),
    ('build', 'строить'),
    ('buy', 'покупать'),
    ('catch', 'ловить'),
    ('choose', 'выбирать'),
    ('cut', 'резать'),
    ('do', 'делать'),
    ('draw', 'рисовать'),
    ('drive', 'водить'),
    ('fall', 'падать'),
    ('feel', 'чувствовать'),
    ('fight', 'драться'),
    ('find', 'находить'),
    ('fly', 'летать'),
    ('forget', 'забывать'),
    ('get', 'получать'),
    ('grow', 'расти'),
  ]),
  _cat('irregular2', 'Глаголы 2', 'Irregular H–S', Icons.bolt_outlined, [
    ('have', 'иметь'),
    ('hear', 'слышать'),
    ('hide', 'прятать'),
    ('hit', 'ударять'),
    ('hold', 'держать'),
    ('hurt', 'ранить'),
    ('keep', 'хранить'),
    ('leave', 'уходить'),
    ('lend', 'давать в долг'),
    ('lose', 'терять'),
    ('meet', 'встречать'),
    ('pay', 'платить'),
    ('put', 'класть'),
    ('ride', 'ездить верхом'),
    ('run', 'бежать'),
    ('say', 'сказать'),
    ('sell', 'продавать'),
    ('send', 'посылать'),
    ('sing', 'петь'),
    ('sit', 'сидеть'),
    ('spend', 'тратить'),
    ('stand', 'стоять'),
    ('swim', 'плавать'),
  ]),
  _cat('irregular3', 'Глаголы 3', 'Irregular T–W', Icons.bolt_outlined, [
    ('teach', 'учить'),
    ('tear', 'рвать'),
    ('tell', 'рассказывать'),
    ('throw', 'бросать'),
    ('understand', 'понимать'),
    ('wake', 'просыпаться'),
    ('wear', 'носить'),
    ('win', 'побеждать'),
    ('forgive', 'прощать'),
    ('freeze', 'замерзать'),
    ('swear', 'клясться'),
    ('sweep', 'подметать'),
    ('shake', 'трясти'),
    ('show', 'показывать'),
    ('shut', 'закрывать'),
  ]),
];

final List<Word> kAllWords = [for (final c in kCategories) ...c.words];

const int kRoundSize = 6;

Category? categoryBySlug(String slug) {
  for (final c in kCategories) {
    if (c.slug == slug) return c;
  }
  return null;
}

List<Word> uniquePool(List<Word> words) {
  final seenEn = <String>{};
  final seenRu = <String>{};
  final out = <Word>[];
  for (final word in words) {
    final en = word.en.toLowerCase();
    final ru = word.ru.toLowerCase();
    if (seenEn.contains(en) || seenRu.contains(ru)) continue;
    seenEn.add(en);
    seenRu.add(ru);
    out.add(word);
  }
  return out;
}

List<Word> pickRound(List<Word> words, List<String> masteredIds,
    {int size = kRoundSize}) {
  final mastered = masteredIds.toSet();
  final unlearned = words.where((w) => !mastered.contains(w.id)).toList();
  final pool = unlearned.length >= size ? unlearned : List<Word>.from(words);
  pool.shuffle();
  return pool.take(size.clamp(0, pool.length)).toList();
}

int masteredInCategory(List<Word> words, List<String> masteredIds) {
  final set = masteredIds.toSet();
  return words.where((w) => set.contains(w.id)).length;
}
